=== WojciechRynczuk/vcdMaker/sources/common/doc/examples/vcdMaker.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT signals   (vector | real | event)*>

<!ELEMENT vector    (   line,
                        timestamp,
                        name,
                        value,
                        size)
>
<!ELEMENT real      (   line,
                        timestamp,
                        name,
                        value)
>
<!ELEMENT event     (   line,
                        timestamp,
                        name)
>
<!ELEMENT line (#PCDATA)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT size (#PCDATA)>

=== WojciechRynczuk/vcdMaker/sources/common/doc/examples/user1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE signals SYSTEM "vcdMaker.dtd">
<signals>

<vector>
    <line>([[:d:]]+):([[:d:]]+)\.([[:d:]]+) Sensors-Magnetometer.Mag([XYZ]+) 0x([0-9a-fA-F]+)</line>
    <timestamp>1000000*dec(/1) + 1000*dec(/2) + dec(/3)</timestamp>
    <name>FRDM.Sensors.Magnetometer.Mag/4</name>
    <value>hex(/5)</value>
    <size>32</size>
</vector>

<vector>
    <line>([[:d:]]+):([[:d:]]+)\.([[:d:]]+) Sensors-Slider 0x([0-9a-fA-F]+)</line>
    <timestamp>1000000*dec(/1) + 1000*dec(/2) + dec(/3)</timestamp>
    <name>FRDM.Sensors.Slider</name>
    <value>hex(/4)</value>
    <size>7</size>
</vector>

<vector>
    <line>([[:d:]]+):([[:d:]]+)\.([[:d:]]+) Buttons-SW([13]+) ([[:d:]]+)</line>
    <timestamp>1000000*dec(/1) + 1000*dec(/2) + dec(/3)</timestamp>
    <name>FRDM.Buttons-SW/4</name>
    <value>dec(/5)</value>
    <size>1</size>
</vector>

<real>
    <line>([[:digit:]]+):([[:digit:]]+)\.([[:digit:]]+) ([[:graph:]]+)-([[:graph:]]+) ([[:digit:][:punct:]]+)</line>
    <timestamp>1000000*dec(/1) + 1000*dec(/2) + dec(/3)</timestamp>
    <name>FRDM./4./5</name>
    <value>/6</value>
</real>

</signals >

=== WojciechRynczuk/vcdMaker/sources/common/doc/examples/vcdMaker.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE signals SYSTEM "vcdMaker.dtd">
<signals>

<vector>
    <line>^#([[:d:]]+) ([[:graph:]]+) ([[:d:]]+) ([[:d:]]+)( +.*)?</line>
    <timestamp>1</timestamp>
    <name>2</name>
    <value>3</value>
    <size>4</size>
</vector>

<real>
    <line>^#([[:d:]]+) ([[:graph:]]+) ([[:d:][:punct:]]+) f( +.*)?</line>
    <timestamp>1</timestamp>
    <name>2</name>
    <value>3</value>
</real>

<event>
    <line>^#([[:d:]]+) ([[:graph:]]+) e( +.*)?</line>
    <timestamp>1</timestamp>
    <name>2</name>
</event>

</signals >

=== WojciechRynczuk/vcdMaker/sources/common/doc/examples/user2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE signals SYSTEM "vcdMaker.dtd">
<signals>

<vector>
    <line>([[:digit:]]+):([[:digit:]]+)\.([[:digit:]]+) Buttons-([[:graph:]]+) 0x([0-9a-fA-F]+)</line>
    <timestamp>1000000*dec(1) + 1000*dec(2) + dec(3)</timestamp>
    <name>"Disco.Buttons." + txt(4)</name>
    <value>dec(5)</value>
    <size>1</size>
</vector>

<real>
    <line>([[:digit:]]+):([[:digit:]]+)\.([[:digit:]]+) ([[:graph:]]+)-([[:graph:]]+) ([[:digit:][:punct:]]+)</line>
    <timestamp>1000000*dec(1) + 1000*dec(2) + dec(3)</timestamp>
    <name>"Disco." + txt(4) + "." + txt(5)</name>
    <value>/6</value>
</real>

<event>
    <line>([[:digit:]]+):([[:digit:]]+)\.([[:digit:]]+) Sync.*</line>
    <timestamp>1000000*dec(1) + 1000*dec(2) + dec(3)</timestamp>
    <name>"Disco.Sync"</name>
</event>

</signals >
